name:                FauxCombinator
version:             0.1.0.0
github:              "faux-combinator/haskell"
license:             BSD-3-Clause
author:              "Ven de Thiel"
maintainer:          "karp@hotmail.fr"
copyright:           "2023 Ven de Thiel"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/faux-combinator/haskell/>

dependencies:
- base >= 4.7 && < 5
- mtl >= 2.3.1
- hspec

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wmissing-deriving-strategies

library:
  source-dirs: src

tests:
  FauxCombinator-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - FauxCombinator
